config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'
  resources :like_albums, only: [:create, :destroy]
  resources :like_photos, only: [:create, :destroy]
  get 'discover/index', to: "discover#index"
  root to: 'feed#index'
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :users do
    resources :albums, shallow:true
    resources :photos, shallow: true do
      member do
        delete "delete_for_album"
      end
    end
    member do
      patch "update_password"
    end
  end

  resources :relationships, only: [:create, :destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  #
end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/album.rb
class Album < ApplicationRecord
  # Validate attributes
  validates :title, presence: true, length: { maximum: 140 }
  validates :description, presence: true, length: { maximum: 300 }
  validates :sharing_status, presence: true
  validates :photos, presence: true
  validates :photos, length: {minimum: 1, message: 'Album should have at least 1 photo defined.'}
  validates :photos, length: {maximum: 25, message: 'Album should have at most 25 photo defined.'}
  validates_associated :photos

  # Associations
  enum sharing_status: {
    limited: 0,
    shared: 1
  }

  belongs_to :user
  has_many :album_photos, dependent: :destroy
  has_one_attached :image
  has_many :photos, through: :album_photos
  accepts_nested_attributes_for :photos, :allow_destroy=> true
  has_many :like_albums, dependent: :destroy

  # Callbacks
  before_validation :default_value, on: :create
  before_destroy :delete_image

  private

  def default_value
    if photos.any?
      self.title ||= photos.first.title
      self.description ||= photos.first.description
      self.sharing_status ||= photos.first.sharing_status
    end
  end

  def delete_image
    self.image.purge
  end
end

app/models/album_img.rb
class AlbumImg < ApplicationRecord
end

app/models/album_photo.rb
class AlbumPhoto < ApplicationRecord
  belongs_to :album
  belongs_to :photo
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contain.rb
class Contain < ApplicationRecord
end

app/models/follow.rb
class Follow < ApplicationRecord
end

app/models/like_album.rb
class LikeAlbum < ApplicationRecord
  validates :user_id, uniqueness: {scope: :album_id}
  belongs_to :user
  belongs_to :album
end

app/models/like_photo.rb
class LikePhoto < ApplicationRecord
  validates :user_id, uniqueness: {scope: :photo_id}
  belongs_to :user
  belongs_to :photo
end

app/models/manage.rb
class Manage < ApplicationRecord
end

app/models/photo.rb
class Photo < ApplicationRecord
  validates :title , presence:true ,length: {maximum:140}
  validates :description , presence:true,length: {maximum:300}
  validates :sharing_status , presence:true
  validates :image , presence: true
  enum sharing_status: {
    limited: 0,
    shared: 1,
  }
  belongs_to :user
  has_many :album_photos
  has_many :albums, through: :album_photos
  has_many :like_photos, dependent: :destroy
  has_one_attached :image
  before_destroy :delete_image
  after_validation :default_value
  private
    def default_value
      self.sharing_status ||= 1
    end
    def delete_image
      self.image.purge
    end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  validates :follower_id, uniqueness: {scope: :followed_id}
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  def active_for_authentication?
      super && self.status == "active"
  end

  def inactive_message
      "Sorry, this account has been deactivated."
  end
  enum status: {inactive: 0 , active: 1}
  has_one_attached :avatar
  #Validate
  validates :first_name, presence: true, length: {maximum: 25}
  validates :last_name, presence: true, length: {maximum: 25}
  validates :email, presence: true,length: {maximum:255}, uniqueness:true, format: { with: URI::MailTo::EMAIL_REGEXP }
  # validates :password, presence: true, length: {maximum:64}
  # validates :password , confirmation: true
  #association
  has_many :photos, dependent: :destroy
  has_many :albums, dependent: :destroy
  has_many :like_photos , dependent: :destroy
  has_many :like_albums , dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  after_validation :default_value
  private
    def default_value
      self.status ||= 1
      self.is_admin ||= false
    end

end

app/controllers/feed_controller.rb
class FeedController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @mode = params[:mode].presence || "PHOTO"
    if user_signed_in?
      @user_followings = current_user.active_relationships.pluck(:followed_id)
        if @mode == "PHOTO"
          @posts = Photo.where(user_id: @user_followings).where(sharing_status: "shared").where(album_id: nil)
        else
          @posts = Album.where(user_id: @user_followings).where(sharing_status: "shared")
        end
    else
        if @mode == "PHOTO"
          @posts = Photo.where(sharing_status: "shared").where(album_id: nil).order(created_at: :desc)
        else
          @posts = Album.where(sharing_status: "shared").order(created_at: :desc)
        end

    end
    if params[:search] == "yes" && params[:key].present?
      key = "%#{params[:key].downcase}%"
      if @mode == "PHOTO"
        @posts = @posts.joins(:user).where("lower(photos.title) LIKE ? or lower(photos.description) LIKE ? or lower(users.first_name) LIKE ? or lower(users.last_name) LIKE ?", key, key, key, key)
      else
        @posts = @posts.joins(:user).where("lower(albums.title) LIKE ? or lower(albums.description) LIKE ? or lower(users.first_name) LIKE ? or lower(users.last_name) LIKE ?", key, key, key, key)
      end
    end
      @posts = @posts.order(created_at: :desc)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/discover_helper.rb
module DiscoverHelper
end

app/helpers/feed_helper.rb
module FeedHelper
end

app/helpers/like_albums_helper.rb
module LikeAlbumsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/feed/_post.html.slim
  = javascript_include_tag 'album.js'
  .picture.position-relative
    .row.h-100.position-relative
      .col-6.h-100.position-relative(data-bs-toggle="modal", data-bs-target="#exampleModal-#{post.id}")
        == image_tag post.image, class:"img-fluid img-thumbnail w-100 h-100" if post.image?
      .col-6.h-100.position-relative
        .row.h-100.position-relative.py-2
          .col-md-12
            .row.pe-2
              .col-9.d-flex.align-items-center
                = link_to image_tag(post.user.avatar,class:"avatar align-items-center") ,user_path(post.user.id) if post.user.avatar?
                = link_to post.user.first_name + " " + post.user.last_name, user_path(post.user.id), class: "d-flex float-start mt-1 name text-decoration-none "
              .col-3.position-relative.mt-2
                - if controller_name == "discover" && current_user.id != post.user.id
                  - relationship = current_user.active_relationships.find_by(followed_id: post.user.id)
                  - if relationship.nil?
                    = button_to "follow", relationships_path, params: {relationship: {followed_id: post.user.id}}, method: :post, class: "btn follow_label btn-outline-warning position-absolute"
                  - else
                    = button_to "following", relationship_path(relationship), method: :delete, class: "btn following_label btn-outline-warning position-absolute"
          .col-md-12
            h5.title_post =post.title
          .col-md-12.h-50.position-relative
            p.h-100.description = post.description

          .col-md-12.post_info.align-items-center
            -if user_signed_in?
              -if @mode == "PHOTO"
                - like = current_user.like_photos.find_by(photo_id: post.id)
                - if like.nil?
                  = button_to like_photos_path , params: {like_photo: {photo_id: post.id}}, method: :post, class: "button_like" do
                    .d-flex.flex-row
                      i.fa-sharp.fa-solid.fa-heart.fa-beat.icon_heart.me-1.text-secondary
                      p.number-icon
                        = (post.like_photos.size).to_s
                - else
                  = button_to like_photo_path(like), method: :delete, class: "button_like" do
                    .d-flex.flex-row
                      i.fa-sharp.fa-solid.fa-heart.fa-beat.icon_heart.me-1
                      p.number-icon
                        = (post.like_photos.size).to_s
              -else
                - like = current_user.like_albums.find_by(album_id: post.id)
                - if like.nil?
                  = button_to like_albums_path , params: {like_album: {album_id: post.id}}, method: :post, class: "button_like" do
                    .d-flex.flex-row
                      i.fa-sharp.fa-solid.fa-heart.fa-beat.icon_heart.me-1.text-secondary
                      p.number-icon
                        = (post.like_albums.size).to_s
                - else
                  = button_to like_album_path(like), method: :delete, class: "button_like" do
                    .d-flex.flex-row
                      i.fa-sharp.fa-solid.fa-heart.fa-beat.icon_heart.me-1
                      p.number-icon
                        = (post.like_albums.size).to_s
            -else
              -if @mode == "PHOTO"
                = button_to like_photos_path , params: {like_photo: {photo_id: post.id}}, method: :post, class: "button_like" do
                  .d-flex.flex-row
                    i.fa-sharp.fa-solid.fa-heart.fa-beat.icon_heart.me-1.text-secondary
                    p.number-icon
                      = (post.like_photos.size).to_s
              -else
                = button_to like_albums_path , params: {like_album: {album_id: post.id}}, method: :post, class: "button_like" do
                  .d-flex.flex-row
                    i.fa-sharp.fa-solid.fa-heart.fa-beat.icon_heart.me-1.text-secondary
                    p.number-icon
                      = (post.like_albums.size).to_s
            p.time-post.w-md-100.w-50 =post.created_at.in_time_zone(+7).strftime("%I:%M %p %d/%m/%Y").downcase
      .modal.fade(id="exampleModal-#{post.id}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true")
        .modal-dialog.modal-lg.modal-dialog-scrollable
          .modal-content.px-3.py-3.position-relative
            i.fa.fa-close.modal-close(data-bs-dismiss="modal" aria-label="Close")
            h5.d-block.font-weight-bold.title_post.mt-3.d-flex.float-start =post.title
            .modal-body
              -if @mode == "PHOTO"
                - if post.image.attached?
                  = image_tag post.image, class: 'd-block img-fluid image_carousel mb-3'
                p.description1 = post.description
              -else
                - if post.photos.any?
                  .carousel.slide.mb-3.carousel-fade(id="mycarousel-#{post.id}")
                    div.carousel-inner
                      -post.photos.each_with_index do |photo, index|
                        div class="carousel-item h-75 #{'active' if index == 0}"
                          - if photo.image.attached?
                            = image_tag photo.image, class: 'd-block img-fluid image_carousel mb-3'
                          p.description1 = photo.description
                  a.carousel-control-prev(href="#mycarousel-#{post.id}" role="button" data-bs-slide="prev")
                    span.carousel-control-prev-icon(aria-hidden="true")
                    span.sr-only Previous
                  a.carousel-control-next(href="#mycarousel-#{post.id}" role="button" data-bs-slide="next")
                    span.carousel-control-next-icon(aria-hidden="true")
                    span.sr-only Next
                - else
                  p No photos available.

app/views/feed/index.html.slim
= javascript_include_tag 'album.js'
body.feeds
  .container-fluid.mt-3
    .row
      .col-md-2
        - if user_signed_in?
          .d-flex.justify-content-center
            = render partial: "layouts/sidebar"
      .col-md-8.px-4.py-3.g-1.text-center.main_feeds
        == form_with url: { action: "index", params: params.permit(:mode) }, method: :get, class: "group_mode" do |form|
          = form.submit "PHOTO", name: "mode", value: "PHOTO", class: "btn btn-lg btn-outline-primary", id: (@mode == "PHOTO" ? "photo_mode" : "album_mode")
          = form.submit "ALBUM", name: "mode", value: "ALBUM", class: "btn btn-lg btn-outline-primary", id: (@mode == "ALBUM" ? "photo_mode" : "album_mode")
        - @posts.each_slice(2) do |post_group|
          .row.my-4
            - post_group.each do |post|
              .col-lg-6.col-12.text-center.post1
                == render partial: "post", locals: {post: post}