config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'
  resources :like_albums, only: [:create, :destroy]
  resources :like_photos, only: [:create, :destroy]
  get 'discover/index', to: "discover#index"
  root to: 'feed#index'
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :users do
    resources :albums, shallow:true
    resources :photos, shallow: true do
      member do
        delete "delete_for_album"
      end
    end
    member do
      patch "update_password"
    end
  end

  resources :relationships, only: [:create, :destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  #
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  def active_for_authentication?
      super && self.status == "active"
  end

  def inactive_message
      "Sorry, this account has been deactivated."
  end
  enum status: {inactive: 0 , active: 1}
  has_one_attached :avatar
  #Validate
  validates :first_name, presence: true, length: {maximum: 25}
  validates :last_name, presence: true, length: {maximum: 25}
  validates :email, presence: true,length: {maximum:255}, uniqueness:true, format: { with: URI::MailTo::EMAIL_REGEXP }
  # validates :password, presence: true, length: {maximum:64}
  # validates :password , confirmation: true
  #association
  has_many :photos, dependent: :destroy
  has_many :albums, dependent: :destroy
  has_many :like_photos , dependent: :destroy
  has_many :like_albums , dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  after_validation :default_value
  private
    def default_value
      self.status ||= 1
      self.is_admin ||= false
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  skip_before_action :authenticate_user!, only: [:index, :show]
  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    if params[:mode].present?
      @mode = params[:mode]
    else
      @mode = "photos"
    end
    if @mode == "photos"
      if user_signed_in? && @user.id == current_user.id
        @posts = Photo.where(user_id: @user.id).where(album_id: nil).order(created_at: :desc)
      else
        @posts = Photo.where(user_id: @user.id,sharing_status:"shared").where(album_id: nil).order(created_at: :desc)
      end
    elsif @mode == "albums"
      if user_signed_in? && @user.id == current_user.id
        @posts = Album.where(user_id: @user.id).order(created_at: :desc)
      else
        @posts = Album.where(user_id: @user.id,sharing_status:"shared").order(created_at: :desc)
      end
      elsif @mode == "followings"
      @posts = User.where(id: @user.active_relationships.pluck(:followed_id))
    else
      @posts = User.where(id: @user.passive_relationships.pluck(:follower_id))
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if params[:user][:password].blank?
        params[:user].delete(:password)
      end
      if params[:user][:status].blank?
        params[:user].delete(:status)
      else
        params[:user][:status] = "inactive" if params[:user][:status] == "0"
        params[:user][:status] = "active" if params[:user][:status] == "1"
      end
      if @user.update(user_params)
        if (current_user.is_admin && current_user.id == @user.id) || (! current_user.is_admin)
          format.html { redirect_to user_path(id:current_user.id, mode: "photos"), notice: "User was successfully updated." }
        else
          format.html { redirect_to admin_index_path(mode: "user"), notice: "User was successfully updated." }
        end
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end

    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      if current_user.is_admin
        format.html{ redirect_to admin_index_path(mode: "user"), notice: "User was successfully destroyed."}
      else
        format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      end

      format.json { head :no_content }
    end
  end

  def update_password
    @user = current_user
    if @user.update_with_password(user_params_change_password)
      bypass_sign_in @user, scope: :user
      redirect_to root_path, notice: "Password was successfully updated."
    else
      render "edit", status: :unprocessable_entity
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_name,:last_name,:avatar,:email,:password,:status)
    end
    def user_params_change_password
      params.require(:user).permit(:current_password, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_albumInfo.html.slim
div.position-relative
  div class="#{ (user_signed_in? && current_user.is_admin) ? 'album_post_admin position-relative' : 'album_post position-relative'}"
    - if user_signed_in? && !current_user.is_admin && post.sharing_status == "limited"
      i.fa.fa-lock.private_icon
    - if post.image.attached?
      - image_class = (user_signed_in? && current_user.is_admin) ? 'img_album_post1_admin rounded-2' : 'h-100 img_album_post1 rounded-2 open-modal-image'
      = image_tag post.image, class: image_class, data: { bs_toggle: "modal", bs_target: "#exampleModal-#{post.id}" }

    - if user_signed_in? && current_user.is_admin
      p.title_album_post.text-truncate.opacity-75.fw-bold.px-5 = post.title
      = link_to edit_album_path(post) do
        i.fa.fa-edit.fa-lg.edit_icon
    - else
      - if user_signed_in? && post.user_id == current_user.id
        .number_photos.opacity-50.d-flex.flex-column.pt-2
          h5 = post.photos.size
          h6 PHOTOS
        = link_to "EDIT", edit_album_path(post), method: :get, class: "btn btn-sm change_photo_btn btn-outline-light opacity-75 rounded-1"
    - if post.image.attached?
      - image_class = (user_signed_in? && current_user.is_admin) ? 'img_album_post2_admin rounded-2' : 'h-100 img_album_post2 rounded-2'
      = image_tag post.image, class: image_class

      - image_class = (user_signed_in? && current_user.is_admin) ? 'img_album_post3_admin rounded-2' : 'h-100 img_album_post3 rounded-2'
      = image_tag post.image, class: image_class

  - if !user_signed_in? || (user_signed_in? && !current_user.is_admin)
    .text-secondary.h6.mt-2.text_title_post.text-truncate.w-75 = post.title

.modal.fade(id="exampleModal-#{post.id}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true")
  .modal-dialog.modal-lg.modal-dialog-scrollable
    .modal-content.px-3.py-3.position-relative
      i.fa.fa-close.modal-close(data-bs-dismiss="modal" aria-label="Close")
      h5.d-block.font-weight-bold.title_post.mt-3.d-flex.float-start = post.title
      .modal-body
        .carousel.slide.mb-3.carousel-fade(id="mycarousel-#{post.id}")
          - if post.photos.any?
            div.carousel-inner
              - post.photos.each_with_index do |photo, index|
                div class="carousel-item h-75 #{'active' if index == 0}"
                  -if photo.image.attached?
                    = image_tag photo.image, class: 'd-block img-fluid image_carousel mb-3'
                  p.description1 = photo.description
          - else
            p No photos available.

        a.carousel-control-prev(href="#mycarousel-#{post.id}" role="button" data-bs-slide="prev")
          span.carousel-control-prev-icon(aria-hidden="true")
          span.sr-only Previous
        a.carousel-control-next(href="#mycarousel-#{post.id}" role="button" data-bs-slide="next")
          span.carousel-control-next-icon(aria-hidden="true")
          span.sr-only Next

app/views/users/_editUser.html.slim
= javascript_include_tag 'album.js'
= form_with(model: @user) do |form|
  - if @user.errors.any?
    div style="color: red"
      h2 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      ul
        - @user.errors.each do |error|
          li = error.full_message
  container.text-center.mb-5
    .row.justify-content-center
      .col.col-lg-2
      .col-md-10.pt-3.col-10
        .d-flex.flex-row.align-items-center
          div.w-25
          .ava_edit_block.rounded-3
            - if user.avatar.attached?
              = image_tag(user.avatar, class: "ava_edit rounded-3 position-relative", id:"edit_img")
            - else
              = image_tag("https://vnn-imgs-a1.vgcloud.vn/image1.ictnews.vn/_Files/2020/03/17/trend-avatar-1.jpg", class: "ava_edit rounded-3 position-relative", id:"edit_img")
            == button_tag "CHANGE",class: "btn btn-sm change-avatar opacity-75", onclick:"document.getElementById('ava_upload').click(); return false;"
            == form.file_field :avatar,type: "file", class: "invisible",id:"ava_upload", onchange:"readURL(this,'edit_img','ava');"
        .d-flex.flex-row.align-items-center.mt-4
          div.w-25
          h6.text-primary-emphasis
            |Basic Information
        .d-flex.flex-row.align-items-center.mb-3
          = form.label :first_name, "First Name", class: "form_title text-black w-25"
          = form.text_field :first_name, placeholder: "First Name", autofocus: true ,class: "form-control text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis w-50"
        .d-flex.flex-row.align-items-center.mb-3
            = form.label :last_name, "Last Name", class: "form_title text-black w-25"
            = form.text_field :last_name, placeholder: "Last Name", class: "form-control text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis w-50"
        .d-flex.flex-row.align-items-center.mb-3
            = form.label :email, "Email", class: "form_title text-black w-25"
            = form.text_field :email, placeholder: "Email", class: "form-control text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis w-50"
        .d-flex.flex-row.align-items-center.mb-3
            = form.label :password, "Password", class: "form_title text-black w-25"
            = form.password_field :password, placeholder:"*********",class: "form-control text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis w-50"
        .d-flex.flex-row.align-items-center.mb-3
            = form.label :status, "Active?", class: "form_title text-black w-25"
            = form.check_box :status, checked:  (user.status == "active"),class: "mt-2" , id: "user_status", onchange: "updateStatus(this.checked)"
        .d-flex.flex-row.align-items-center.mb-3
            div.w-25
            = form.submit "Save", class: "save-button px-3 text-light bg-success"

app/views/users/_form.html.slim
= javascript_include_tag 'album.js'
= form_with(model: @user) do |form|
  - if @user.errors.any?
    == action_name
    div style="color: red"
      h2 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      ul
        - @user.errors.each do |error|
          li = error.full_message
  container.text-center.mb-5
    .row.justify-content-center
      .col.col-lg-2
      .col-md-10.pt-3.col-10
        .d-flex.flex-row.align-items-center
          div.w-25
          .ava_edit_block.rounded-3
            - if user.avatar.attached?
              = image_tag(user.avatar, class: "ava_edit rounded-3 position-relative", id:"edit_img")
            - else
              = image_tag("https://vnn-imgs-a1.vgcloud.vn/image1.ictnews.vn/_Files/2020/03/17/trend-avatar-1.jpg", class: "ava_edit rounded-3 position-relative", id:"edit_img")
            == button_tag "CHANGE",class: "btn btn-sm change-avatar opacity-75", onclick:"document.getElementById('ava_upload').click(); return false;"
            == form.file_field :avatar,  direct_upload: true ,type: "file", class: "invisible",id:"ava_upload", onchange:"readURL(this,'edit_img','ava');"
        .d-flex.flex-row.align-items-center.mt-4
          div.w-25
          h6.text-primary-emphasis
            |Basic Information
        .d-flex.flex-row.align-items-center.mb-3
          = form.label :first_name, "First Name", class: "form_title text-black w-25"
          = form.text_field :first_name, placeholder: "First Name", autofocus: true ,class: "form-control text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis w-50"
        .d-flex.flex-row.align-items-center.mb-3
            = form.label :last_name, "Last Name", class: "form_title text-black w-25"
            = form.text_field :last_name, placeholder: "Last Name", class: "form-control text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis w-50"
        .d-flex.flex-row.align-items-center.mb-3
            = form.label :email, "Email", class: "form_title text-black w-25"
            = form.text_field :email, placeholder: "Email", class: "form-control text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis w-50"
        .d-flex.flex-row.align-items-center.mb-3
            div.w-25
            = form.submit "Save", class: "save-button px-3 text-light bg-success"

app/views/users/_form_change_password.html.slim
= javascript_include_tag 'album.js'
= form_for(@user, :url => { :action => "update_password" } ) do |form|
  - if @user.errors.any?
    div style="color: red"
      h2 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      ul
        - @user.errors.each do |error|
          li = error.full_message
  container.text-center
    .row.justify-content-center
      .col.col-lg-2
      .col-md-10.pt-3.col-10
        .d-flex.flex-row.align-items-center.mt-4
          div.w-25
          h6.text-primary-emphasis
            |Password
        .d-flex.flex-row.align-items-center.mb-3
          = form.label :current_password, "Current Password", class: "form_title text-black w-25"
          = form.password_field :current_password, placeholder: "***************", class: "form-control text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis w-50 "
        .d-flex.flex-row.align-items-center.mb-3
            = form.label :password, "New Password", class: "form_title text-black w-25"
            = form.password_field :password, placeholder: "New password", class: "form-control text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis w-50"
        .d-flex.flex-row.align-items-center.mb-3
            = form.label :password_confirmation, "Password Confirmation", class: "form_title text-black w-25"
            = form.password_field :password_confirmation, placeholder: "Confirmation password", class: "form-control text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis text-secondary-emphasis w-50"
        .d-flex.flex-row.align-items-center.mb-3
            div.w-25
            = form.submit "Save", class: "save-button px-3 text-light bg-success"

app/views/users/_manageUser.html.slim
table.table.table-hover
  thead
    tr.fw-bolder
      td First Name
      td Last Name
      td Email
      td Last login
      td
      td
  tbody
    - posts.each do |post|
      tr.h6
        td = post.first_name
        td = post.last_name
        td = post.email
        td = post.created_at
        td
          = button_to "Edit", edit_user_path(post),method: :get ,class: "btn btn-sm btn-success px-3"
        td
          = button_to "Delete", user_path(post), method: :delete,class: "btn btn-sm btn-danger px-2"

app/views/users/_photoInfo.html.slim
div.position-relative
    .album_post.position-relative
        - if user_signed_in? && !current_user.is_admin && post.sharing_status == "limited"
            i.fa.fa-lock.private_icon
        -if post.image.attached?
            = image_tag post.image, class: 'h-100 img_album_post1 rounded-2 open-modal-image', data: { bs_toggle: "modal", bs_target: "#exampleModal-#{post.id}" }
        -if user_signed_in? && current_user.is_admin
            p.title_album_post.text-truncate.opacity-75.fw-bold.px-5 =post.title
            = link_to edit_photo_path(post) do
                i.fa.fa-edit.fa-lg.edit_icon
        -else
            -if user_signed_in? && post.user_id == current_user.id
                = link_to "EDIT",edit_photo_path(post), class: "btn btn-sm change_photo_btn opacity-75 btn-outline-dark rounded-3"
    -if !user_signed_in? || (user_signed_in? && !current_user.is_admin)
        .text-secondary.h6.mt-1.text_title_post.text-truncate.w-75
            = post.title
.modal.fade(id="exampleModal-#{post.id}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true")
    .modal-dialog.modal-lg.modal-dialog-scrollable
        .modal-content.px-3.py-3.position-relative
            i.fa.fa-close.modal-close(data-bs-dismiss="modal" aria-label="Close")
            h5.d-block.font-weight-bold.title_post.mt-3.d-flex.float-start =post.title
            .modal-body
              = image_tag(post.image, class: "img img-fluid mb-3")
              p.description1 == post.description

app/views/users/_user.html.slim
= javascript_include_tag 'album.js'
.row.mb-4
  .col-3
    = image_tag user.avatar, class: "avatar_info" if user.avatar.attached?
  .col-md-9.col-10
    .d-flex.flex-column.float-start
      .d-flex.float-start
        -if user_signed_in?
          - if  current_user.id == user.id
            = link_to "Edit profile", edit_user_path(user), class: "btn btn-outline-primary btn_edit_profile mt-md-0 mt-3 ms-md-0 ms-4"
          - else
            - relationship = current_user.active_relationships.find_by(followed_id: user.id)
            - if relationship.nil?
              = button_to "follow", relationships_path, params: {relationship: {followed_id: user.id}}, method: :post, class: "btn btn-outline-light btn-sm px-4 rounded-4 follow_button"
            - else
              = button_to "following", relationship_path(relationship), method: :delete, class: "btn btn-outline-light btn-sm px-4 rounded-4 following_button"
      h1.mt-2.d-flex.float-start
        = user.first_name + " " + user.last_name
      .d-flex.flex-row.text-black-50
        = button_to user_path, params: {mode: "photos"}, method: :get, class: "btn btn-sm btn-outline-light d-flex flex-row me-1 me-md-2 color_button #{mode == "photos" ? "text-primary" : "text-secondary" }", id: 'photos' do
          h2
            - if user_signed_in? && user.id == current_user.id
              = user.photos.where(album_id: nil).size
            - else
              = user.photos.where(album_id: nil, sharing_status: "shared").size
          .mt-3.ms-1.hr_vertical.fw-bold.pe-md-4.pe-1 PHOTOS
        = button_to user_path, params: {mode: "albums"}, method: :get, class: "btn btn-sm btn-outline-light d-flex flex-row me-1 me-md-2 color_button #{mode == "albums" ? "text-primary": "text-secondary" }" , id:'albums' do
          h2
            - if user_signed_in? && user.id == current_user.id
              = user.albums.size
            - else
              = user.albums.where(sharing_status: "shared").size
          .mt-3.ms-1.hr_vertical.fw-bold.pe-md-4.pe-1 ALBUMS
        = button_to user_path, params: {mode: "followings"}, method: :get, class: "btn btn-sm btn-outline-light d-flex flex-row me-1 me-md-2 color_button #{mode == "followings" ? "text-primary" : "text-secondary" }", id: 'followings' do
          h2 = user.active_relationships.size
          .mt-3.ms-1.hr_vertical.fw-bold.pe-md-4.pe-1 FOLLOWINGS
        = button_to user_path, params: {mode: "followers"}, method: :get, class: "btn btn-sm btn-outline-light d-flex flex-row me-1 me-md-2 color_button #{mode == "followers" ? "text-primary" : "text-secondary" }", id: 'followers' do
          h2 = user.passive_relationships.size
          .mt-3.ms-1.fw-bold.pe-md-4.pe-1 FOLLOWERS

- if mode == "photos" || mode == "albums"
  - if user_signed_in? && current_user.id == user.id
    - if mode == "photos"
      .d-flex.justify-content-end
        = link_to "Add Photo", new_user_photo_path(user.id), class: "btn btn-success btn-sm btn-outline-warning btn-md text-light rounded-4 fw-bold mb-4"
    - else
      .d-flex.justify-content-end
        = link_to "Add Album", new_user_album_path(user.id), class: "btn btn-success btn-sm btn-outline-warning btn-md text-light rounded-4 fw-bold mb-4"
  - posts.each_slice(4) do |post_group|
    .row
      - post_group.each do |post|
        .col-lg-3.col-6.text-center.post_photo
          - if mode == "photos"
            == render partial: "photoInfo", locals: {post: post, mode: mode}
          -else
            = render partial: "albumInfo", locals: {post: post, mode: mode}
- else
  - posts.each_slice(4) do |post_group|
    .row
      - post_group.each do |post|
        .col-lg-3.col-6.text-center.post_photo1
          == render partial: "userInfo", locals: {user: post, mode: mode}

app/views/users/_userInfo.html.slim
.post_user.py-2.d-flex.flex-column.position-relative.pb-4
    = image_tag user.avatar , class: "avatar_user" if user.avatar.attached?
    h5
        = link_to user.first_name.titleize + " " + user.last_name.titleize , user_path(user.id), class: "text-decoration-none text-black"
    .row.align-items-center.gx-4
        .col-6.d-block.align-items-center
            h4.fw-bold.text-primary
                = user.photos.size
            h6.text-primary.number_description
                | PHOTOS
        .col-6
            h4.fw-bold.text-primary
                = user.albums.size
            h6.text-primary.number_description
                | PHOTOS
    div.row.d-flex.justify-content-center.align-items-center.mx-auto
        - if user_signed_in? && current_user.id != user.id
            - follow =  current_user.active_relationships.find_by(followed_id: user.id)
            - if follow.nil?
                div.d-block.mb-1
                    = button_to "follow", relationships_path, params: {relationship: {followed_id: user.id}}, method: :post, class: "btn follow_label btn-outline-warning w-50 ms-5"
            - else
                div.d-block.mb-1
                    = button_to "following", relationship_path(follow), method: :delete, class: "btn following_label btn-outline-warning w-50 ms-5"

app/views/users/edit.html.slim
body.feeds
    .container.mt-3
        .row
            .col-md-2
              == render "layouts/sidebar"
            .col-md-8.px-4.py-3.g-1.main_feeds
              .title_new_post Edit User Profile
              hr
              - if current_user.is_admin && current_user.id != @user.id
                == render partial: "editUser", locals: {user: @user, mode: "photos"}
              -else
                == render partial: "form", locals: { user: @user, mode: "photos"}
                == render partial: "form_change_password", locals: {user: @user}

app/views/users/index.html.slim
/ #users
/   - @users.each do |user|
/     == render user
/     p
/       = link_to "Show this user", user

/ = link_to "New user", new_user_path

app/views/users/new.html.slim
h1 New user

== render "form", user: @user

br

div
  = link_to "Back to users", users_path

app/views/users/show.html.slim
= javascript_include_tag 'album.js'
body.feeds
  .container.mt-3
    .row
      .col-md-2
        - if user_signed_in?
          == render "layouts/sidebar"
      .col-md-8.px-4.py-3.g-1.text-center.main_feeds
        == render partial: "user", locals: {user: @user, mode: @mode, posts: @posts}

        / div

        /   '|
        /   =< link_to "Back to users", users_path

        /   = button_to "Destroy this user", @user, method: :delete