config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'
  resources :like_albums, only: [:create, :destroy]
  resources :like_photos, only: [:create, :destroy]
  get 'discover/index', to: "discover#index"
  root to: 'feed#index'
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :users do
    resources :albums, shallow:true
    resources :photos, shallow: true do
      member do
        delete "delete_for_album"
      end
    end
    member do
      patch "update_password"
    end
  end

  resources :relationships, only: [:create, :destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  #
end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/album.rb
class Album < ApplicationRecord
  # Validate attributes
  validates :title, presence: true, length: { maximum: 140 }
  validates :description, presence: true, length: { maximum: 300 }
  validates :sharing_status, presence: true
  validates :photos, presence: true
  validates :photos, length: {minimum: 1, message: 'Album should have at least 1 photo defined.'}
  validates :photos, length: {maximum: 25, message: 'Album should have at most 25 photo defined.'}
  validates_associated :photos

  # Associations
  enum sharing_status: {
    limited: 0,
    shared: 1
  }

  belongs_to :user
  has_many :album_photos, dependent: :destroy
  has_one_attached :image
  has_many :photos, through: :album_photos
  accepts_nested_attributes_for :photos, :allow_destroy=> true
  has_many :like_albums, dependent: :destroy

  # Callbacks
  before_validation :default_value, on: :create
  before_destroy :delete_image

  private

  def default_value
    if photos.any?
      self.title ||= photos.first.title
      self.description ||= photos.first.description
      self.sharing_status ||= photos.first.sharing_status
    end
  end

  def delete_image
    self.image.purge
  end
end

app/models/album_img.rb
class AlbumImg < ApplicationRecord
end

app/models/album_photo.rb
class AlbumPhoto < ApplicationRecord
  belongs_to :album
  belongs_to :photo
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contain.rb
class Contain < ApplicationRecord
end

app/models/follow.rb
class Follow < ApplicationRecord
end

app/models/like_album.rb
class LikeAlbum < ApplicationRecord
  validates :user_id, uniqueness: {scope: :album_id}
  belongs_to :user
  belongs_to :album
end

app/models/like_photo.rb
class LikePhoto < ApplicationRecord
  validates :user_id, uniqueness: {scope: :photo_id}
  belongs_to :user
  belongs_to :photo
end

app/models/manage.rb
class Manage < ApplicationRecord
end

app/models/photo.rb
class Photo < ApplicationRecord
  validates :title , presence:true ,length: {maximum:140}
  validates :description , presence:true,length: {maximum:300}
  validates :sharing_status , presence:true
  validates :image , presence: true
  enum sharing_status: {
    limited: 0,
    shared: 1,
  }
  belongs_to :user
  has_many :album_photos
  has_many :albums, through: :album_photos
  has_many :like_photos, dependent: :destroy
  has_one_attached :image
  before_destroy :delete_image
  after_validation :default_value
  private
    def default_value
      self.sharing_status ||= 1
    end
    def delete_image
      self.image.purge
    end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  validates :follower_id, uniqueness: {scope: :followed_id}
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  def active_for_authentication?
      super && self.status == "active"
  end

  def inactive_message
      "Sorry, this account has been deactivated."
  end
  enum status: {inactive: 0 , active: 1}
  has_one_attached :avatar
  #Validate
  validates :first_name, presence: true, length: {maximum: 25}
  validates :last_name, presence: true, length: {maximum: 25}
  validates :email, presence: true,length: {maximum:255}, uniqueness:true, format: { with: URI::MailTo::EMAIL_REGEXP }
  # validates :password, presence: true, length: {maximum:64}
  # validates :password , confirmation: true
  #association
  has_many :photos, dependent: :destroy
  has_many :albums, dependent: :destroy
  has_many :like_photos , dependent: :destroy
  has_many :like_albums , dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  after_validation :default_value
  private
    def default_value
      self.status ||= 1
      self.is_admin ||= false
    end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: %i[ show edit update destroy delete_for_album ]

  # GET /photos or /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1 or /photos/1.json
  def show
  end
  def delete_for_album
    @photo.destroy
    redirect_to edit_album_path(id:params[:album_id]), notice: "Photo was successfully destroyed"
  end
  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos or /photos.json
  def create
    @photo = Photo.new(photo_params)
    @photo.user_id = current_user.id
    respond_to do |format|
      if @photo.save
        format.html { redirect_to user_path(current_user, mode: "photos"), notice: "Photo was successfully created." }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1 or /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html do
          if !current_user.is_admin
            redirect_to user_path(current_user, mode: "photos"), notice: "Photo was successfully updated."
          else
            redirect_to admin_index_path(mode: "photo"), notice: "Photo was successfully updated."
          end
        end
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1 or /photos/1.json
  def destroy
      @user_id = @photo.user_id
      @photo.destroy
      respond_to do |format|
        format.html do
          if (current_user.is_admin && current_user.id == @user_id)|| (!current_user.is_admin)
            redirect_to user_path(current_user, mode: "photos"), notice: "Photo was successfully destroyed."
          else
            redirect_to admin_index_path(mode: "photo"), notice: "Photo was successfully destroyed."
          end
        end
        format.json { head :no_content }
        format.js   { render layout: false }
      end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def photo_params
      params.require(:photo).permit(:title,:description,:image,:sharing_status)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/discover_helper.rb
module DiscoverHelper
end

app/helpers/feed_helper.rb
module FeedHelper
end

app/helpers/like_albums_helper.rb
module LikeAlbumsHelper
end

app/helpers/like_photos_helper.rb
module LikePhotosHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/photos/_form.html.slim
= javascript_include_tag 'album.js'
== form_with model: @photo, url: user_photos_path, method: "post" do |form|
  - if @photo.errors.any?
    div style="color: red"
      h2 = "#{pluralize(@photo.errors.count, "error")} prohibited this photo from being saved:"
      ul
        - @photo.errors.each do |error|
          li = error.full_message

  div.container
    .div
      .row
        .col-6.mb-3
          .row.gy-2
            .col-12
              == form.label :title, class: "form_title text-black"
              == form.text_field :title, autofocus: true, placeholder: "Photo Title", class: "form-control"
            .col-md-6.col-9
              .div.d-flex.flex-column
                == form.label :sharing_status ,"Sharing Mode", class: "form_title text-black"
                == form.select :sharing_status, [['public','shared'],['private','limited']], {selected: 'shared'}, { class: "btn btn-md dropdown-toggle dropdown-toggle-split text-secondary border border-dark form_control1" }
        .col-6.d-flex.flex-column
          == form.label :description, class: "form_title text-black"
          == form.text_area :description, placeholder: "Photo Description", class: "form_control1 h-75"
        .col-12
          .row.g-1.mt-3
            .col-4.col-md-3.d-none#block_img onclick="deleteImage()"
              = image_tag("",id:"img_prev",class:"position-relative")

              .delete-icon.w-75
                i.fa-sharp.fa-solid.fa-xmark.fa-xl

            .col-4.col-md-3#block_change_img
              == button_tag id: "files", onclick:"document.getElementById('file').click(); return false;"
                i.fa-solid.fa-plus.icon_plus
              == form.file_field :image , type: "file", class: "invisible", id:"file", onchange:"readURL(this,'img_prev','edit');"
    = form.submit "Save", method: "post", class: "btn_create_post mt-1 btn btn-md"

app/views/photos/_form_edit.html.slim
= javascript_include_tag 'album.js'
== form_with model: @photo, url: photo_path, method: "patch", class: "position-relative" do |form|
  - if @photo.errors.any?
    div style="color: red"
      h2 = "#{pluralize(@photo.errors.count, "error")} prohibited this photo from being saved:"
      ul
        - @photo.errors.each do |error|
          li = error.full_message

  div.container-fuild
    .div
      .row.mb-3
        .col-6.mb-3
          .row
            .col-12
              == form.label :title, class: "form_title text-black"
              == form.text_field :title, autofocus: true, placeholder: "Photo Title", class: "form-control"
            .col-md-6.col-9
              .div.d-flex.flex-column
                == form.label :sharing_status ,"Sharing Mode", class: "form_title text-black"
                == form.select :sharing_status, [['public','shared'],['private','limited']], {selected: @photo.sharing_status}, { class: "btn btn-md dropdown-toggle dropdown-toggle-split text-secondary border border-dark form_control1" }
        .col-6.d-flex.flex-column
          == form.label :description, class: "form_title text-black"
          == form.text_area :description, placeholder: "Photo Description", class: "form_control1 h-75"
        .col-12
          .row.g-1.mt-3
            - if photo.image.attached?
              .col-4.col-md-3#block_img
                = image_tag(photo.image,id:"img_prev",class:"position-relative")
                .delete-icon.w-75 onclick="deleteImage()"
                  i.fa-sharp.fa-solid.fa-xmark.fa-xl
              .col-4.col-md-3.d-none#block_change_img
                == button_tag id: "files", onclick:"document.getElementById('file').click(); return false;"
                  i.fa-solid.fa-plus.icon_plus
                == form.file_field :image , type: "file", class: "invisible", id:"file", onchange:"readURL(this,'img_prev','edit');"
    .d-flex.flex-row.mt-2
      = form.submit "Save", method: "post", class: "btn btn_create_post btn-md"
      = link_to '#', class: 'btn btn-md btn_destroy_post ', data: { bs_toggle: 'modal', bs_target: '#exampleModal' } do
        .d-flex.flex-row.text-center.align-items-center
          i.fa-solid.fa-trash-can
          p.m-0.ms-2 Delete


.modal.fade(id="exampleModal" tabindex="0" aria-labelledby="exampleModalLabel" aria-hidden="true")
  .modal-dialog
    .modal-content
      .modal-header
        h5.modal-title#exampleModalLabel Delete Confirmation
        i.fa.fa-close.modal-close(data-bs-dismiss="modal" aria-label="Close")
      .modal-body
        | Are you sure?
      .modal-footer
        button.btn.btn-primary(data-bs-dismiss="modal") Close
        = button_to photo, method: :delete, class: "btn btn-danger"
          |Delete

app/views/photos/_photo.html.slim
div id="#{dom_id photo}"

app/views/photos/edit.html.slim
body.feeds
    .container.mt-3
        .row
            .col-md-2
              == render "layouts/sidebar"
            .col-md-8.px-4.py-3.g-1.main_feeds
              .title_new_post Edit Photo
              .d-flex.justify-content-end
                = link_to "Back", user_path(current_user.id), class: "btn btn-primary px-3 btn-sm btn_back"
              hr
                == render "form_edit", photo: @photo

app/views/photos/index.html.slim
p style="color: green" = notice

h1 Photos

#photos
  - @photos.each do |photo|
    == render photo
    p
      = link_to "Show this photo", photo

= link_to "New photo", new_photo_path

app/views/photos/new.html.slim
body.feeds
    .container.mt-3
        .row
            .col-md-2
              == render "layouts/sidebar"
            .col-md-8.px-4.py-3.g-1.main_feeds
              .title_new_post New Photo
              hr
                == render "form", photo: @photo
              / div
              / = link_to "Back to albums", user_albums_path

app/views/photos/show.html.slim
p style="color: green" = notice

== render @photo

div
  => link_to "Edit this photo", edit_photo_path(@photo)
  '|
  =< link_to "Back to photos", user_photos_path(current_user)

  = button_to "Destroy this photo", @photo, method: :delete