config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'
  resources :like_albums, only: [:create, :destroy]
  resources :like_photos, only: [:create, :destroy]
  get 'discover/index', to: "discover#index"
  root to: 'feed#index'
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :users do
    resources :albums, shallow:true
    resources :photos, shallow: true do
      member do
        delete "delete_for_album"
      end
    end
    member do
      patch "update_password"
    end
  end

  resources :relationships, only: [:create, :destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  #
end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/album.rb
class Album < ApplicationRecord
  # Validate attributes
  validates :title, presence: true, length: { maximum: 140 }
  validates :description, presence: true, length: { maximum: 300 }
  validates :sharing_status, presence: true
  validates :photos, presence: true
  validates :photos, length: {minimum: 1, message: 'Album should have at least 1 photo defined.'}
  validates :photos, length: {maximum: 25, message: 'Album should have at most 25 photo defined.'}
  validates_associated :photos

  # Associations
  enum sharing_status: {
    limited: 0,
    shared: 1
  }

  belongs_to :user
  has_many :album_photos, dependent: :destroy
  has_one_attached :image
  has_many :photos, through: :album_photos
  accepts_nested_attributes_for :photos, :allow_destroy=> true
  has_many :like_albums, dependent: :destroy

  # Callbacks
  before_validation :default_value, on: :create
  before_destroy :delete_image

  private

  def default_value
    if photos.any?
      self.title ||= photos.first.title
      self.description ||= photos.first.description
      self.sharing_status ||= photos.first.sharing_status
    end
  end

  def delete_image
    self.image.purge
  end
end

app/models/album_img.rb
class AlbumImg < ApplicationRecord
end

app/models/album_photo.rb
class AlbumPhoto < ApplicationRecord
  belongs_to :album
  belongs_to :photo
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contain.rb
class Contain < ApplicationRecord
end

app/models/follow.rb
class Follow < ApplicationRecord
end

app/models/like_album.rb
class LikeAlbum < ApplicationRecord
  validates :user_id, uniqueness: {scope: :album_id}
  belongs_to :user
  belongs_to :album
end

app/models/like_photo.rb
class LikePhoto < ApplicationRecord
  validates :user_id, uniqueness: {scope: :photo_id}
  belongs_to :user
  belongs_to :photo
end

app/models/manage.rb
class Manage < ApplicationRecord
end

app/models/photo.rb
class Photo < ApplicationRecord
  validates :title , presence:true ,length: {maximum:140}
  validates :description , presence:true,length: {maximum:300}
  validates :sharing_status , presence:true
  validates :image , presence: true
  enum sharing_status: {
    limited: 0,
    shared: 1,
  }
  belongs_to :user
  has_many :album_photos
  has_many :albums, through: :album_photos
  has_many :like_photos, dependent: :destroy
  has_one_attached :image
  before_destroy :delete_image
  after_validation :default_value
  private
    def default_value
      self.sharing_status ||= 1
    end
    def delete_image
      self.image.purge
    end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  validates :follower_id, uniqueness: {scope: :followed_id}
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  def active_for_authentication?
      super && self.status == "active"
  end

  def inactive_message
      "Sorry, this account has been deactivated."
  end
  enum status: {inactive: 0 , active: 1}
  has_one_attached :avatar
  #Validate
  validates :first_name, presence: true, length: {maximum: 25}
  validates :last_name, presence: true, length: {maximum: 25}
  validates :email, presence: true,length: {maximum:255}, uniqueness:true, format: { with: URI::MailTo::EMAIL_REGEXP }
  # validates :password, presence: true, length: {maximum:64}
  # validates :password , confirmation: true
  #association
  has_many :photos, dependent: :destroy
  has_many :albums, dependent: :destroy
  has_many :like_photos , dependent: :destroy
  has_many :like_albums , dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  after_validation :default_value
  private
    def default_value
      self.status ||= 1
      self.is_admin ||= false
    end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/discover_helper.rb
module DiscoverHelper
end

app/helpers/feed_helper.rb
module FeedHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.slim
= javascript_include_tag 'album.js'
body.feeds
  .container-fluid.mt-3
    .row
      .col-md-2
        - if user_signed_in?
          .d-flex.justify-content-center
            == render "layouts/sidebar"
      .col-md-8.px-4.py-3.g-1.text-center.main_feeds
        -if @mode == "photo" || @mode == "album"
          - @posts.each_slice(4) do |post_group|
            .row
              - post_group.each do |post|
                .col-lg-3.col-6.text-center.post_photo
                  - if @mode == "photo"
                    == render partial: "users/photoInfo", locals: {post: post, mode: @mode, pagy:@pagy}
                  - else
                    == render partial: "users/albumInfo", locals: {post: post, mode: @mode, pagy: @pagy}
        - else
          .row
            == render partial: "users/manageUser", locals: {posts: @posts, mode: @mode, pagy: @pagy}
        .d-flex.justify-content-center.mt-4
          == pagy_bootstrap_nav(@pagy)

app/views/layouts/_navbar.html.slim
nav.navbar.navbar-expand.d-flex.bg-body-info.position-relative
  .container-fluid
    .collapse.navbar-collapse#navbarTogglerDemo03.ps-md-5.ps-1
      = link_to root_path, class: "navbar-brand title text-decoration-none text-light ms-md-5 ms-1 text-lg"
        -if user_signed_in?
          -if current_user.is_admin
            |Fotobook Admin
          -else
            |Fotobook
        -else
            |Fotobook
      - if defined?(@mode) && (@mode == "PHOTO" || @mode == "ALBUM")
        - mode = @mode
      -else
        - mode = "PHOTO"

      - if controller_name == "feed"
        = form_with url: root_path, method: :get, class: "d-flex col-md-6 search_bar ms-md-5 ms-2" do |form|
          = form.text_field :key, placeholder: 'Search Photo / Album', class: "form_control px-2 me-md-2 me-0 d-block w-75"
          = form.hidden_field :search, :value => "yes"
          = form.hidden_field :mode, :value => mode
          = form.submit "Search", class: "btn btn-outline-light btn-md ms-md-3 ms-1 me-3 me-md-3 fw-bold"
      -else
        = form_with url: discover_index_path, method: :get, class: "d-flex col-md-6 search_bar ms-md-5 ms-2" do |form|
          = form.text_field :key, placeholder: 'Search Photo / Album', class: "form_control px-2 me-md-2 me-0 d-block w-75"
          = form.hidden_field :search, :value => "yes"
          = form.hidden_field :mode, :value => mode
          = form.submit "Search", class: "btn btn-outline-light btn-md ms-md-3 ms-1 me-3 me-md-3 fw-bold"

      - if user_signed_in?
        .col-md-2.me-4
          .d-flex.align-items-center
            = link_to image_tag(current_user.avatar ,class:"img-fluid avatar") ,user_path(current_user) if current_user.avatar.attached?
            = link_to current_user.first_name + " " + current_user.last_name,user_path(current_user), class: "ms-md-2 ms-1 text-justify name text-decoration-none text-light fs-6"
        = link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link end-0 me-md-5 me-md-1"
      - else
        = link_to "Login", new_user_session_path, class: "nav-link end-0 me-md-5 me-3"

app/views/layouts/_sidebar.html.slim
.sidebar
    -if current_user.is_admin
        = button_to admin_index_path, params: {mode: "photo"}, method: :get,  class: ( @mode == "photo" ? "left_title1" : "left_title") do
            |Manage Photos
        = button_to admin_index_path, params: {mode: "album"}, method: :get ,class: ( @mode == "album" ? "left_title1" : "left_title") do
            |Manage Albums
        = button_to admin_index_path, params: {mode: "user"}, method: :get, class: ( @mode == "user" ? "left_title1" : "left_title") do
            |Manage Users
    - else
        = link_to "Feeds", root_path, class: (controller_name == "feed" ? "left_title1" : "left_title")
        = link_to "Discover", discover_index_path, class: (controller_name == "discover" ? "left_title1" : "left_title")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fotobook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%=javascript_include_tag 'album.js' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <%= stylesheet_link_tag "custom", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <% if notice %><div class="alert alert-info"> <%= notice %> </div> <%end%>
    <% if alert %><div class="alert alert-warning"> <%= alert %></div> <%end%>
    <% if flash[:success] %><div class="alert alert-success"> <%= flash[:success] %></div> <%end%>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
            crossorigin="anonymous"></script>
    <turbo-frame id="turbo_frame"></turbo-frame>
  </body>
</html>